server:
  port: 8080
  servlet:
    context-path:
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/firstdb?serverTimezone=Europe/Moscow
    username: root
    password: root
